// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  awards: dynamic(() => import("./Awards")),
  footer: dynamic(() => import("./Footer")),
  header: dynamic(() => import("./Header")),
  header_top: dynamic(() => import("./HeaderTop")),
  hero: dynamic(() => import("./Hero")),
  instagram: dynamic(() => import("./Instagram")),
  portfolio: dynamic(() => import("./Portfolio")),
  services: dynamic(() => import("./Services")),
  testimonials: dynamic(() => import("./Testimonials")),
};
